name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag abhishekganji27/stackdemo:${{ github.run_number }}
    
    - name: Push the Docker image
      run: docker push abhishekganji27/stackdemo:${{ github.run_number }}
