name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v4
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag abhishekganji27/stackdemo:${{ github.run_number }}
  
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ vars.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push the Docker image
    #   run: docker push abhishekganji27/stackdemo:${{ github.run_number }}
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        path: main
      
    - name: Checkout k8s-argocd repo
      uses: actions/checkout@v4
      with:
        repository: abhishekganji27/k8s-argocd
        path: k8s-manifests

    - name: files
      run: |
        ls
        pwd
        
    - name: checkout to main and list
      run: |
        cd main
        ls
        pwd
        cd ..
        pwd
        
        
    - name: checkout to k8s-manifest branch and list
      run: |
        pwd
        cd k8s-manifests/stackdemo
        ls
