name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      IMAGE_NAME: abhishekganji27/stackdemo:${{ github.run_number }}
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v4
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag $IMAGE_NAME
  
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ vars.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push the Docker image
    #   run: docker push $IMAGE_NAME
      
    - name: Checkout k8s-argocd repo
      uses: actions/checkout@v4
      with:
        repository: abhishekganji27/k8s-argocd
        path: k8s-manifests
    
    - name: cat kustomization.yaml in k8s-manifests/stackdemo dir
      run: |
        # cd k8s-manifests/stackdemo
        # echo "file system contents"
        # ls
        echo "cat k11n.yaml"
        cat k8s-manifests/stackdemo/kustomization.yaml
        
    - name: update image tag in k11n.yaml
      uses: mikefarah/yq@master
      with:
        cmd: "yq -i '.images[0].newTag: \"${{ github.run_number }}\"' k8s-manifests/stackdemo/kustomization.yaml"

    
    # - name: git config
    #   run: |
    #     git config user.email 
    #     git config user.name 
    
    - name: git branch
      run: cd k8s-manifests/stackdemo && git branch && ls && git status
        
    - name: push changes in kustomization.yaml in k8s-manifests/stackdemo dir
      run: |
        pwd 
        ls
        cd k8s-manifests
        ls
        cd stackdemo
        ls
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

        git add .
        git commit -m "modified kustomization.yaml "
        git push origin main

    # - name: cat kustomization.yaml in k8s-manifests/stackdemo dir
    #   uses: stefanzweifel/git-auto-commit-action@v5
    #   with:
    #     commit_message: Modified kustomization.yaml 
    # - name: git config
    #   run: |
    #     git config user.email 
    #     git config user.name 


    # - name: modify kustomization.yaml in k8s-manifests/stackdemo dir
    #   run: |
    #     cd k8s-manifests/stackdemo
        # echo "file system contents"
        # ls
        # echo "cat kusto.yaml"
        # cat kustomization.yaml

        # yq -i ".images[0].newTag: \"${{ github.run_number }}\"" kustomization.yaml
         
        
        # echo "\n\ncat kusto.yaml"
        # cat kustomization.yaml

        # git --version

        # git remote -v 


        
